name: Construir una App en NEXTJS
on: push
jobs:
    build-project:
        name: Construccion del Proyecto
        runs-on: ubuntu-latest
        steps:
            - name: Checkout del codigo
              uses: actions/checkout@v4
            - name: Instalar Dependencias
              run: npm install
            - name: Ejecutar en produccion
              run: npm run build
            - name: Crear y subir artefactos
              uses: actions/upload-artifact@v4
              with:
                name: nuevo-sitio
                path: .next/
    download-project:
        name: Construccion del Proyecto
        runs-on: ubuntu-latest
        steps:
            - name: Descargar artefacto
              uses: actions/download-artifact@v4
              with:
                name: nuevo-sitio
            - name: Display structure of downloaded files
              run: ls -R

